stages:
- stage: Stage1
  jobs:

  # Set an output variable from job A
  - job: Aaaaa
    pool:
      vmImage: 'vs2017-win2016'aaaa
    steps:
    - powershell: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the value"aaaa
      name: setvarStep
    - script: echo $(setvarStep.myOutputVar)aaaa
      name: echovar

  # Map the variable into job B
  - job: B
    dependsOn: A
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
      myVarFromJobA: $[ dependencies.A.outputs['setvarStep.myOutputVar'] ]  # map in the variable
                                                                            # remember, expressions require single quotes
    steps:
    - script: echo $(myVarFromJobA)
      name: echovar